On Ubuntu, run customize script which activates ExtensionImages

diff --git a/boot/customize/init b/boot/customize/init
--- a/boot/customize/init
+++ b/boot/customize/init
@@ -1,4 +1,11 @@
-#!/bin/bash
+#!/bin/bash -x
+
+# Yellow text
+echo -e '\E[33;40m'"\033[1m"
+
+# Be verbose
+HERE="$(dirname "$(readlink -f "${0}")")"
+echo "$HERE running"
 
 # Mount first FAT partition that is mounted read-write
 # assuming this is the partition that holds the Live ISO
@@ -15,7 +22,7 @@ try() {
 
 # Fedora; based on
 # http://anderson.the-silvas.com/2014/02/14/fedora-20-on-a-macbook-pro-13-late-2013-retina-display/
-#if [ -e /etc/redhat-release ] ; then
+if [ -e /usr/libexec/gsd-backlight-helper ] ; then
   try /usr/libexec/gsd-backlight-helper --set-brightness 4
   try rfkill block bluetooth # TODO: Disable Bluetooth
   echo 50 > /sys/class/leds/smc::kbd_backlight/brightness
@@ -26,9 +33,7 @@ try() {
   for DEVICE in $(find /sys/bus/pci/devices/*) ; do
     echo "auto" > $DEVICE/power/control
   done
-#fi
-
-exit 0
+fi
 
 # Configure dconf
 # Obtained with dconf watch /
@@ -41,15 +46,106 @@ dconf write /org/gnome/settings-daemon/peripherals/touchpad/motion-acceleration 
 dconf write /org/gnome/settings-daemon/peripherals/touchpad/scroll-method 'two-finger-scrolling'
 dconf write /org/gnome/settings-daemon/peripherals/touchpad/tap-to-click true
 dconf write /org/gnome/settings-daemon/peripherals/touchpad/disable-while-typing false
-# Fix Retina display (works on Ubuntu)
-# dconf write /com/ubuntu/user-interface/scale-factor {'eDP1': 12}
-dconf write /org/gnome/desktop/interface/cursor-size 36
-# dconf write /org/gnome/desktop/interface/scaling-factor uint32 1
-dconf write /org/gnome/desktop/interface/text-scaling-factor 1.5
-dconf write /org/compiz/profiles/unity/plugins/expo/x-offset 97
-dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-capture-mouse false
-dconf write /org/compiz/profiles/unity/plugins/unityshell/num-launchers 1
+# Fix Retina display (works on Ubuntu), TODO: Make this run only on Retina devices
+# dconf write /org/gnome/desktop/interface/cursor-size 36
+# dconf write /org/gnome/desktop/interface/text-scaling-factor 1.5
+# dconf write /org/compiz/profiles/unity/plugins/expo/x-offset 97
+# dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-capture-mouse false
+# dconf write /org/compiz/profiles/unity/plugins/unityshell/num-launchers 1
 EOF
 
 # Alternatively, could set the resolution to non-Retina
 # dconf write /org/compiz/profiles/unity/plugins/core/outputs ['1440x900+0+0']
+
+# Disable crash reporter
+sed -i -e 's|enabled=1|enabled=0|g' /etc/default/apport 2>/dev/null
+
+# No restricted driver nagging in Ubuntu
+echo "Hidden=true" >> /etc/xdg/autostart/jockey-gtk.desktop
+
+# Remove dist-upgrade nag screen
+mv /usr/lib/update-manager/check-new-release-gtk /usr/lib/update-manager/check-new-release-gtk.disabled 2>/dev/null
+
+# Disable gnome-keyring
+mv /usr/bin/gnome-keyring-daemon /usr/bin/gnome-keyring-daemon.disabled || echo "Could not disable gnome-keyring"
+
+# Disable GNOME Login Sound
+echo "X-GNOME-Autostart-enabled=false" > /usr/share/gnome/autostart/libcanberra-login-sound.desktop
+
+# Remove crap from desktop
+find /home/ -wholename "*Desktop/*.desktop" -exec rm {} \;
+
+# FN keys on Apple keyboard
+cat > /etc/modprobe.d/hid_apple.conf <<EOF
+options hid_apple fnmode=2
+EOF
+rmmod hid_apple 2>/dev/null && modprobe hid_apple
+
+# Dualhead on, works for NVidia on Ubuntu 11.04 at least
+cat > /etc/X11/Xsession.d/80dualhead <<\EOF
+xrandr --output VGA-1 --right-of DVI-I-1
+EOF
+
+# Add universe
+sed -i -e 's|main restricted|main universe multiverse restricted|g' /etc/apt/sources.list
+
+# Disable apt translations
+rm /var/lib/apt/lists/*_i18n_*
+cat >> /etc/apt/apt.conf <<EOF
+Acquire {
+           Languages "none";
+};
+EOF
+
+# Fix major KDE4 annoyances. See
+# http://techbase.kde.org/KDE_System_Administration/PlasmaDesktopScripting#Examples
+# On non-Kubuntu systems, the following locations might be relevant as well:
+# /usr/share/kde4/apps/plasma-desktop/init/00-defaultLayout.js
+# /usr/share/kde4/apps/plasma/layout-templates/org.kde.plasma-desktop.defaultPanel/contents/layout.js
+KDE4EVILFILE="/usr/share/kubuntu-default-settings/kde4-profile/default/share/apps/plasma-desktop/init/00-defaultLayout.js"
+ls "${KDE4EVILFILE}" 2>/dev/null && (
+# Proper K menu
+sed -i -e 's|launcher|simplelauncher|g' "${KDE4EVILFILE}"
+# Proper icons on desktop
+sed -i -e 's|new Activity(\"desktop\")|new Activity(\"folderview\")|g' "${KDE4EVILFILE}"
+# No more box around the desktop icons
+sed -i -e 's|folderview = activity.addWidget(\"folderview\");||g' "${KDE4EVILFILE}"
+sed -i -e 's|folderview.writeConfig(\"url\", \"desktop:/\");||g' "${KDE4EVILFILE}"
+# No more crap
+sed -i -e 's|activity.addWidget("twitter");||g' "${KDE4EVILFILE}"
+# No more sounds
+mkdir -p "/etc/skel/.kde/share/config/"
+cat > "/etc/skel/.kde/share/config/knotifyrc" <<\EOF
+[Sounds]
+No sound=true
+Use external player=false
+Volume=100
+EOF
+)
+
+# Revert stupidity that prevents running bash files from FAT disks
+sed -i -e 's|showexec|\x00\x00\x00\x00\x00\x00\x00\x00|g' /usr/lib/udisks/udisks-daemon
+sed -i -e 's|showexec|\x00\x00\x00\x00\x00\x00\x00\x00|g' /usr/lib/udisks2/udisksd # Ubuntu 12.10
+
+# Mount .ExtensionImage files
+ARCH=$(uname -p)
+EXTENSIONS=$(find $HERE/$ARCH/ -type f -name *ExtensionImage)
+EXTDIR=/var/run/Extensions
+mkdir -p "${EXTDIR}"
+for EXTENSION in $EXTENSIONS ; do
+  SHORT=$(basename "${EXTENSION}")
+  mkdir -p "${EXTDIR}"/"${SHORT}"
+  mount -o loop,ro "${EXTENSION}" "${EXTDIR}"/"${SHORT}"
+done
+
+EXTENSIONS=$(mount | grep ExtensionImage | cut -d " " -f 3)
+for EXTENSION in $EXTENSIONS ; do
+  cp -rsf "${EXTENSION}"/* /
+  if [ -x "${EXTENSION}"/ExtensionRun ] ; then
+     "${EXTENSION}"/ExtensionRun
+  fi
+done
+
+# Continue as usual
+tput sgr0
+grep -r init= /proc/cmdline && exec /sbin/init
